-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE DATABASE ISMS;

CREATE TABLE IF NOT EXISTS public.announcement
(
    announcement_id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    message character varying(255) COLLATE pg_catalog."default",
    department_id integer,
    year_level_id integer,
    staff_id integer,
    "Type" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT announcement_pkey PRIMARY KEY (announcement_id)
);

CREATE TABLE IF NOT EXISTS public.course
(
    course_id serial NOT NULL,
    course_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT course_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    department_id serial NOT NULL,
    department_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT department_pkey PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS public.admin
(
    staff_id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    contact_number character varying(15) COLLATE pg_catalog."default",
    department_id integer,
    CONSTRAINT admin_pkey PRIMARY KEY (staff_id)
);

CREATE TABLE IF NOT EXISTS public.student
(
    student_id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    contact_number character varying(15) COLLATE pg_catalog."default",
    year_level_id integer,
    department_id integer,
    course_id integer,
    CONSTRAINT student_pkey PRIMARY KEY (student_id)
);

CREATE TABLE IF NOT EXISTS public.year_level
(
    year_level_id serial NOT NULL,
    year_level character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT year_level_pkey PRIMARY KEY (year_level_id)
);

ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES public.admin (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcement
    ADD CONSTRAINT announcement_year_level_id_fkey FOREIGN KEY (year_level_id)
    REFERENCES public.year_level (year_level_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.admin
    ADD CONSTRAINT admin_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT student_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT student_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT student_year_level_id_fkey FOREIGN KEY (year_level_id)
    REFERENCES public.year_level (year_level_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;